url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Prompter Pub" # the name of your site, e.g. ACME Corp.
description: "A place where i do talk a bit about me, and about my experience with prompting"
