url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Prompt Pub" # the name of your site, e.g. ACME Corp.
description: "A place where i do talk about my experience with prompting, and where to discover a bit about me!"
