menu:
- {name: 'post', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'about me', url: '/courses'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Malinverno Luca', 
title: 'Porini Innovation & Research Center Lead', 
department: 'R&D',
 institution: 'Porini SRL', 
 institution_address: 'Via Cavour 2, Lomazzo (CO) - Italy', 
 phone: '+39 347.3686306', 
 email: 'luca.malinverno@porini.it', 
  image: 'assets/img/avatar_001.jpg'}
